// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantManager.Data;

#nullable disable

namespace RestaurantManager.Migrations
{
    [DbContext(typeof(RestaurantManagerContext))]
    [Migration("20241011152858_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantManager.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FK_User")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FK_User")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Admin@gmail.com",
                            FK_User = 5,
                            PasswordHashed = "$2a$11$uwRLWFky/foDrhxGCyOSwekoZLp8.ytnU2lypaODvVST2H4xOo0.a",
                            isAdmin = true
                        },
                        new
                        {
                            Id = 2,
                            Email = "User@gmail.com",
                            FK_User = 6,
                            PasswordHashed = "$2a$11$9xUzyEt5ZyUMfAXA/83AOeW4vZL3nPDLWFUta2P031LLq8urLvxvC",
                            isAdmin = false
                        });
                });

            modelBuilder.Entity("RestaurantManager.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FK_RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("FK_TableId")
                        .HasColumnType("int");

                    b.Property<int>("FK_TimeslotId")
                        .HasColumnType("int");

                    b.Property<int>("FK_UserID")
                        .HasColumnType("int");

                    b.Property<int>("NrOfPeople")
                        .HasColumnType("int");

                    b.Property<string>("Requests")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("requestedEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("requestedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FK_RestaurantId");

                    b.HasIndex("FK_TableId");

                    b.HasIndex("FK_TimeslotId");

                    b.HasIndex("FK_UserID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RestaurantManager.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FK_RestaurantId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FK_RestaurantId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FK_RestaurantId = 1,
                            Name = "Meny"
                        },
                        new
                        {
                            Id = 2,
                            FK_RestaurantId = 2,
                            Name = "Meny"
                        },
                        new
                        {
                            Id = 3,
                            FK_RestaurantId = 2,
                            Name = "Helgmeny"
                        });
                });

            modelBuilder.Entity("RestaurantManager.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountSold")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FK_MenuId")
                        .HasColumnType("int");

                    b.Property<int>("FK_RestaurantId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FK_MenuId");

                    b.HasIndex("OrderId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountSold = 70,
                            Category = "Pizza",
                            Description = "En sorts pizza.",
                            FK_MenuId = 1,
                            FK_RestaurantId = 1,
                            IsAvailable = true,
                            Name = "Ananaspizza",
                            Price = 90
                        },
                        new
                        {
                            Id = 2,
                            AmountSold = 90,
                            Category = "Pizza",
                            Description = "En annan pizza.",
                            FK_MenuId = 1,
                            FK_RestaurantId = 1,
                            IsAvailable = true,
                            Name = "Bananpizza",
                            Price = 80
                        },
                        new
                        {
                            Id = 3,
                            AmountSold = 80,
                            Category = "Pizza",
                            Description = "Också pizza.",
                            FK_MenuId = 1,
                            FK_RestaurantId = 1,
                            IsAvailable = true,
                            Name = "Bönpizza",
                            Price = 70
                        },
                        new
                        {
                            Id = 4,
                            AmountSold = 40,
                            Category = "Pizza",
                            Description = "En Rund pizza.",
                            FK_MenuId = 1,
                            FK_RestaurantId = 1,
                            IsAvailable = true,
                            Name = "Pastapizza",
                            Price = 60
                        },
                        new
                        {
                            Id = 5,
                            AmountSold = 40,
                            Category = "Dryck",
                            Description = "Lärre.",
                            FK_MenuId = 1,
                            FK_RestaurantId = 1,
                            IsAvailable = true,
                            Name = "Cuba cola",
                            Price = 50
                        },
                        new
                        {
                            Id = 6,
                            AmountSold = 50,
                            Category = "Pasta",
                            Description = "Pasta med pålägg",
                            FK_MenuId = 1,
                            FK_RestaurantId = 1,
                            IsAvailable = true,
                            Name = "Pastasallad med banan",
                            Price = 40
                        },
                        new
                        {
                            Id = 7,
                            AmountSold = 70,
                            Category = "Pasta",
                            Description = "Pasta med annat pålägg",
                            FK_MenuId = 1,
                            FK_RestaurantId = 1,
                            IsAvailable = true,
                            Name = "Pastasallad med mint",
                            Price = 45
                        },
                        new
                        {
                            Id = 8,
                            AmountSold = 90,
                            Category = "Pasta",
                            Description = "Pasta med oätligt pålägg",
                            FK_MenuId = 1,
                            FK_RestaurantId = 1,
                            IsAvailable = true,
                            Name = "Pastasallad med lakrits",
                            Price = 45
                        },
                        new
                        {
                            Id = 9,
                            AmountSold = 50,
                            Category = "Pizza",
                            Description = "Pizza med champinjoner",
                            FK_MenuId = 1,
                            FK_RestaurantId = 1,
                            IsAvailable = true,
                            Name = "Capritjosan",
                            Price = 70
                        },
                        new
                        {
                            Id = 10,
                            AmountSold = 56,
                            Category = "Pizza",
                            Description = "Pizza utan champinjoner",
                            FK_MenuId = 1,
                            FK_RestaurantId = 1,
                            IsAvailable = true,
                            Name = "Margareta",
                            Price = 71
                        },
                        new
                        {
                            Id = 11,
                            AmountSold = 33,
                            Category = "Dryck",
                            Description = "Brun dryck",
                            FK_MenuId = 1,
                            FK_RestaurantId = 1,
                            IsAvailable = true,
                            Name = "Kaffe",
                            Price = 10
                        },
                        new
                        {
                            Id = 12,
                            AmountSold = 6,
                            Category = "Dryck",
                            Description = "Halvgenomskinlig dryck",
                            FK_MenuId = 1,
                            FK_RestaurantId = 1,
                            IsAvailable = true,
                            Name = "Té",
                            Price = 10
                        },
                        new
                        {
                            Id = 13,
                            AmountSold = 4,
                            Category = "Dryck",
                            Description = "Rosa lärre",
                            FK_MenuId = 1,
                            FK_RestaurantId = 1,
                            IsAvailable = true,
                            Name = "Hallonsoda",
                            Price = 20
                        },
                        new
                        {
                            Id = 14,
                            AmountSold = 4,
                            Category = "Dryck",
                            Description = "Gul lärre",
                            FK_MenuId = 1,
                            FK_RestaurantId = 1,
                            IsAvailable = true,
                            Name = "Lemonad",
                            Price = 20
                        },
                        new
                        {
                            Id = 15,
                            AmountSold = 30,
                            Category = "Dryck",
                            Description = "Orange lärre",
                            FK_MenuId = 1,
                            FK_RestaurantId = 1,
                            IsAvailable = true,
                            Name = "Zingo",
                            Price = 15
                        },
                        new
                        {
                            Id = 16,
                            AmountSold = 20,
                            Category = "Dryck",
                            Description = "Annan brun dryck",
                            FK_MenuId = 1,
                            FK_RestaurantId = 1,
                            IsAvailable = true,
                            Name = "Cola",
                            Price = 15
                        },
                        new
                        {
                            Id = 17,
                            AmountSold = 0,
                            Category = "Dryck",
                            Description = "Halvgenomskinlig dryck",
                            FK_MenuId = 2,
                            FK_RestaurantId = 2,
                            IsAvailable = true,
                            Name = "Té",
                            Price = 100
                        },
                        new
                        {
                            Id = 18,
                            AmountSold = 0,
                            Category = "Bakelser",
                            Description = "Snurrigt bakverk",
                            FK_MenuId = 3,
                            FK_RestaurantId = 2,
                            IsAvailable = true,
                            Name = "Bulle",
                            Price = 100
                        },
                        new
                        {
                            Id = 19,
                            AmountSold = 0,
                            Category = "Bakelser",
                            Description = "Rosa bakverk",
                            FK_MenuId = 3,
                            FK_RestaurantId = 2,
                            IsAvailable = true,
                            Name = "Hallonpaj med grädde",
                            Price = 100
                        },
                        new
                        {
                            Id = 20,
                            AmountSold = 0,
                            Category = "Bakelser",
                            Description = "det är paj",
                            FK_MenuId = 3,
                            FK_RestaurantId = 2,
                            IsAvailable = true,
                            Name = "Blåbärspaj med grädde",
                            Price = 100
                        },
                        new
                        {
                            Id = 21,
                            AmountSold = 0,
                            Category = "Dryck",
                            Description = "Brun dryck",
                            FK_MenuId = 3,
                            FK_RestaurantId = 2,
                            IsAvailable = true,
                            Name = "Kaffe",
                            Price = 100
                        },
                        new
                        {
                            Id = 22,
                            AmountSold = 0,
                            Category = "Dryck",
                            Description = "Halvgenomskinlig dryck",
                            FK_MenuId = 3,
                            FK_RestaurantId = 2,
                            IsAvailable = true,
                            Name = "Té",
                            Price = 100
                        });
                });

            modelBuilder.Entity("RestaurantManager.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FK_RestaurantID")
                        .HasColumnType("int");

                    b.Property<int>("FK_UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FK_RestaurantID");

                    b.HasIndex("FK_UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantManager.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Vällingbygatan 1, 16266 Vällingby",
                            Description = "Sveriges bästa pizzeria",
                            Email = "PazziPizza@gmail.com",
                            Name = "Pazzi Pizza",
                            PhoneNumber = "0731111111"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Astrakangatan 1, 16552 Hässelby",
                            Description = "Världens bästa Café",
                            Email = "CafeKaffe@gmail.com",
                            Name = "Café Kaffe",
                            PhoneNumber = "0732222222"
                        });
                });

            modelBuilder.Entity("RestaurantManager.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FK_RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("NrOfSeats")
                        .HasColumnType("int");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("RestaurantManager.Models.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isAvaliable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("RestaurantManager.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "David@gmail.com",
                            Name = "David Hedman",
                            PhoneNumber = "1111111111"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Leo@gmail.com",
                            Name = "Leo Horrorwitz",
                            PhoneNumber = "1111111122"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Berend@gmail.com",
                            Name = "Berend Mevius",
                            PhoneNumber = "1111111133"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Siri@gmail.com",
                            Name = "Siri Martinsson",
                            PhoneNumber = "1111111144"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Admin@gmail.com",
                            Name = "Adam Min",
                            PhoneNumber = "0707070707"
                        },
                        new
                        {
                            Id = 6,
                            Email = "User@gmail.com",
                            Name = "Userella De Fault",
                            PhoneNumber = "0737373737"
                        });
                });

            modelBuilder.Entity("RestaurantManager.Models.Account", b =>
                {
                    b.HasOne("RestaurantManager.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("RestaurantManager.Models.Account", "FK_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantManager.Models.Booking", b =>
                {
                    b.HasOne("RestaurantManager.Models.Restaurant", "Restaurant")
                        .WithMany("Bookings")
                        .HasForeignKey("FK_RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManager.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("FK_TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManager.Models.TimeSlot", "Timeslot")
                        .WithMany()
                        .HasForeignKey("FK_TimeslotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManager.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("FK_UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("Table");

                    b.Navigation("Timeslot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantManager.Models.Menu", b =>
                {
                    b.HasOne("RestaurantManager.Models.Restaurant", "Restaurant")
                        .WithMany("Menus")
                        .HasForeignKey("FK_RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantManager.Models.MenuItem", b =>
                {
                    b.HasOne("RestaurantManager.Models.Menu", "Menu")
                        .WithMany("MenuItems")
                        .HasForeignKey("FK_MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManager.Models.Order", null)
                        .WithMany("MenuItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("RestaurantManager.Models.Order", b =>
                {
                    b.HasOne("RestaurantManager.Models.Restaurant", "Restaurant")
                        .WithMany("CurrentOrders")
                        .HasForeignKey("FK_RestaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManager.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("FK_UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManager.Models.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantManager.Models.Table", b =>
                {
                    b.HasOne("RestaurantManager.Models.Restaurant", null)
                        .WithMany("Tables")
                        .HasForeignKey("RestaurantId");
                });

            modelBuilder.Entity("RestaurantManager.Models.Menu", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("RestaurantManager.Models.Order", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("RestaurantManager.Models.Restaurant", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CurrentOrders");

                    b.Navigation("Menus");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("RestaurantManager.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
